<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitfa41d3678fcf6753366afd5c7163a8c9
{
    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'MyClub\\MyClubGroups\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'MyClub\\MyClubGroups\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitfa41d3678fcf6753366afd5c7163a8c9::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitfa41d3678fcf6753366afd5c7163a8c9::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitfa41d3678fcf6753366afd5c7163a8c9::$classMap;

        }, null, ClassLoader::class);
    }
}
